[Settings]

ID = "wai-accessibility-principles"

[build]

command = "CI='' bundle exec jekyll build --trace --verbose --config '_config.yml,_config_staging.yml'"
publish = "_site"

[[redirects]]
  from = "/"
  to = "/fundamentals/accessibility-principles/"