[build]

command = "bundle exec jekyll build --trace --verbose --config '_config.yml,_config_staging.yml'"
publish = "_site"

[[redirects]]
  from = "/"
  to = "/fundamentals/accessibility-principles/"